ktor:
    application:
        modules:
            - com.mxrsoon.volare.ApplicationKt.module
    deployment:
        port: "$PORT:8080"

jwt:
  secret: "$JWT_SECRET"
  issuer: "$JWT_ISSUER:https://volare.mxrsoon.com/"
  audience: "$JWT_AUDIENCE:https://volare.mxrsoon.com/"
  realm: "$JWT_REALM:Access to Volare"

db:
  url: "$DB_URL"
  user: "$DB_USER"
  password: "$DB_PASSWORD"

oauth:
  google:
    client-id: "$OAUTH_GOOGLE_CLIENT_ID"
    secret: "$OAUTH_GOOGLE_CLIENT_SECRET"