on:
  push:
    branches:
      - 'main'
      - 'feature/deploy-workflow'

name: 'Deploy to GCE'

jobs:
  deploy:
    name: "Deploy"
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - id: 'setup-ssh-keys'
        name: 'Setup SSH keys'
        env:
          SSH_PRIV_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          SSH_PUB_KEY: ${{ secrets.GCP_SSH_PUBLIC_KEY }}
          SSH_CONFIG: ${{ vars.GCP_SSH_CONFIG }}
        run: |
          mkdir -p ~/.ssh
          chmod 0700 ~/.ssh
          echo $SSH_PRIV_KEY > ~/.ssh/id_gcp
          echo $SSH_PUB_KEY > ~/.ssh/id_gcp.pub
          echo $SSH_CONFIG > ~/.ssh/config
          chmod 600 ~/.ssh/id_gcp
          chmod 600 ~/.ssh/id_gcp.pub
          chmod 600 ~/.ssh/config
          cat ~/.ssh/config

      - id: 'ssh'
        name: 'SSH command'
        run: |
          ssh -F ~/.ssh/config volare-server sudo ls -lA /var/volare