on:
  push:
    branches:
      - 'main'
      - 'feature/deploy-workflow'

name: 'Deploy to GCE'

jobs:
  deploy:
    name: "Deploy"
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      # Configure Workload Identity Federation and generate an access token.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER_NAME }}

      - id: 'setup-sdk'
        name: 'Set up Google Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - id: 'gcloud-info'
        name: 'SSH command'
        run: 'gcloud info'

      - id: 'ssh'
        name: 'SSH command'
        run: 'gcloud compute ssh --zone "us-west1-a" "volare-server" --project "volare-app" --command="sudo ls -lA /var/volare"'

      - name: 'Show Output'
        run: |-
          echo '${{ steps.ssh.outputs.stdout }}'
          echo '${{ steps.ssh.outputs.stderr }}'