on:
  push:
    branches:
      - 'main'
      - 'feature/deploy-workflow'

name: 'Deploy to GCE'

jobs:
  deploy:
    name: "Deploy"
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - id: 'ssh'
        name: 'SSH command'
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.GCP_SSH_HOSTNAME }}
          username: ${{ secrets.GCP_SSH_USERNAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            whoami
            sudo ls -lA /var/volare